// frontend/src/components/Layout/Navbar.jsx
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import './Navbar.css';
import ThemeToggle from '../Common/ThemeToggle';

const Navbar = () => {
    const { user, isAuthenticated, isClient, isAdmin, logout } = useAuth();
    const navigate = useNavigate();

    const handleLogout = () => {
        logout();
        navigate('/login');
    };

    return (
        <nav className="navbar">
            <div className="navbar-container">
                <Link to="/" className="navbar-logo">
                    <span className="logo-icon">🛡️</span>
                    <span className="logo-text">Insurai</span>
                </Link>

                <div className="navbar-links">
                    {!isAuthenticated ? (
                        <>
                            <Link to="/login" className="nav-link">Login</Link>
                            <Link to="/signup" className="nav-link btn-primary">Sign Up</Link>
                        </>
                    ) : isClient ? (
                        <>
                            <Link to="/client" className="nav-link">Dashboard</Link>
                            <Link to="/client/buy-policy" className="nav-link">Buy Policy</Link>
                            <Link to="/client/my-policies" className="nav-link">My Policies</Link>
                            <Link to="/client/claim" className="nav-link">File Claim</Link>
                            <Link to="/client/profile" className="nav-link">Profile</Link>
                            <div className="nav-user">
                                <span className="user-name">{user?.firstName}</span>
                                <button onClick={handleLogout} className="btn btn-logout">Logout</button>
                            </div>
                        </>
                    ) : isAdmin ? (
                        <>
                            <Link to="/admin" className="nav-link">Dashboard</Link>
                            <Link to="/admin/create-policy" className="nav-link">Create Policy</Link>
                            <Link to="/admin/policies" className="nav-link">Manage Policies</Link>
                            <Link to="/admin/claims" className="nav-link">Manage Claims</Link>
                            <Link to="/admin/clients" className="nav-link">Manage Clients</Link>
                            <div className="nav-user">
                                <span className="admin-badge">ADMIN</span>
                                <span className="user-name">{user?.firstName}</span>
                                <button onClick={handleLogout} className="btn btn-logout">Logout</button>
                            </div>
                        </>
                    ) : null}
                </div>
                <ThemeToggle />
            </div>
        </nav>
    );
};

export default Navbar;

// frontend-angular/src/app/shared/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { ThemeToggleComponent } from '../theme-toggle/theme-toggle.component';
import { AuthService } from '../../core/services/auth.service';
import { Observable } from 'rxjs';

@Component({
    selector: 'app-navbar',
    standalone: true,
    imports: [CommonModule, RouterModule, ThemeToggleComponent],
    templateUrl: './navbar.component.html',
    styleUrls: ['./navbar.component.scss']
})
export class NavbarComponent {
    user$: Observable<any>;
    isAuthenticated$: Observable<any>;

    constructor(private authService: AuthService) {
        this.user$ = this.authService.user$;
        this.isAuthenticated$ = this.authService.user$;
    }

    get isClient(): boolean {
        return this.authService.isClient();
    }

    get isAdmin(): boolean {
        return this.authService.isAdmin();
    }

    logout(): void {
        this.authService.logout();
    }
}

<nav class="navbar">
  <div class="navbar-container">
    <a routerLink="/" class="navbar-logo">
      <span class="logo-icon">🛡️</span>
      <span class="logo-text">Insurai</span>
    </a>

    <div class="navbar-links">
      <ng-container *ngIf="!(isAuthenticated$ | async)">
        <a routerLink="/login" class="nav-link">Login</a>
        <a routerLink="/signup" class="nav-link btn-primary">Sign Up</a>
      </ng-container>

      <ng-container *ngIf="isClient">
        <a routerLink="/client" class="nav-link">Dashboard</a>
        <a routerLink="/client/buy-policy" class="nav-link">Buy Policy</a>
        <a routerLink="/client/my-policies" class="nav-link">My Policies</a>
        <a routerLink="/client/claim" class="nav-link">File Claim</a>
        <a routerLink="/client/profile" class="nav-link">Profile</a>
        <div class="nav-user">
          <span class="user-name">{{ (user$ | async)?.firstName }}</span>
          <button (click)="logout()" class="btn btn-logout">Logout</button>
        </div>
      </ng-container>

      <ng-container *ngIf="isAdmin">
        <a routerLink="/admin" class="nav-link">Dashboard</a>
        <a routerLink="/admin/create-policy" class="nav-link">Create Policy</a>
        <a routerLink="/admin/policies" class="nav-link">Manage Policies</a>
        <a routerLink="/admin/claims" class="nav-link">Manage Claims</a>
        <a routerLink="/admin/clients" class="nav-link">Manage Clients</a>
        <div class="nav-user">
          <span class="admin-badge">ADMIN</span>
          <span class="user-name">{{ (user$ | async)?.firstName }}</span>
          <button (click)="logout()" class="btn btn-logout">Logout</button>
        </div>
      </ng-container>
    </div>
    
    <app-theme-toggle></app-theme-toggle>
  </div>
</nav>
