// frontend-angular/src/app/features/client/my-policies/my-policies.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { ClientPolicyService } from '../../../core/services/client-policy.service';
import { ClientPolicy } from '../../../core/models/policy.model';

@Component({
  selector: 'app-my-policies',
  standalone: true,
  imports: [CommonModule, RouterModule],
  template: `
    <div *ngIf="loading" class="loading"><div class="spinner"></div></div>
    <div *ngIf="!loading" class="container" style="padding: 2rem;">
      <h1>My Policies</h1>
      <div *ngIf="policies.length === 0" style="text-align: center; padding: 3rem;">
        <p>You don't have any policies yet.</p>
        <a routerLink="/client/buy-policy" class="btn btn-primary">Buy Your First Policy</a>
      </div>
      <table *ngIf="policies.length > 0" class="policies-table" style="width: 100%; margin-top: 2rem;">
        <thead>
          <tr>
            <th>Policy Name</th>
            <th>Company</th>
            <th>Status</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let policy of policies">
            <td>{{ policy.policyName || 'N/A' }}</td>
            <td>{{ policy.companyName }}</td>
            <td><span [class]="'badge badge-' + getBadgeClass(policy.status)">{{ policy.status }}</span></td>
            <td>{{ policy.startDate | date }}</td>
            <td>{{ policy.endDate | date }}</td>
            <td><button class="btn btn-outline" (click)="renewPolicy(policy.id)">Renew</button></td>
          </tr>
        </tbody>
      </table>
    </div>
  `,
  styles: [`
    th { text-align: left; padding: 1rem; }
    td { padding: 0.75rem 1rem; }
  `]
})
export class MyPoliciesComponent implements OnInit {
  policies: ClientPolicy[] = [];
  loading = true;

  constructor(private clientPolicyService: ClientPolicyService) { }

  ngOnInit(): void {
    this.clientPolicyService.getMyPolicies().subscribe({
      next: (data) => {
        this.policies = data;
        this.loading = false;
      },
      error: () => {
        this.loading = false;
      }
    });
  }

  getBadgeClass(status: string): string {
    return status === 'ACTIVE' ? 'success' : status === 'EXPIRED' ? 'danger' : 'warning';
  }

  renewPolicy(id: number): void {
    this.clientPolicyService.renewPolicy(id).subscribe({
      next: () => {
        alert('Policy renewed successfully!');
        this.ngOnInit();
      }
    });
  }
}

// frontend/src/pages/Client/MyPolicies.jsx
import { useState, useEffect } from 'react';
import { clientPolicyService } from '../../services';
import './MyPolicies.css';

const MyPolicies = () => {
    const [policies, setPolicies] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState('');

    useEffect(() => {
        fetchPolicies();
    }, []);

    const fetchPolicies = async () => {
        try {
            const data = await clientPolicyService.getMyPolicies();
            setPolicies(data);
        } catch (err) {
            setError('Failed to load policies');
        } finally {
            setLoading(false);
        }
    };

    const handleRenew = async (policyId) => {
        try {
            await clientPolicyService.renewPolicy(policyId);
            fetchPolicies(); // Refresh the list
            alert('Policy renewed successfully!');
        } catch (err) {
            alert(err.response?.data?.error || 'Failed to renew policy');
        }
    };

    if (loading) {
        return <div className="loading"><div className="spinner"></div></div>;
    }

    return (
        <div className="my-policies-container container">
            <h1 className="page-title fade-in">My Policies</h1>

            {error && <div className="error-message">{error}</div>}

            {policies.length === 0 ? (
                <div className="empty-state card">
                    <p>You don't have any policies yet.</p>
                    <a href="/client/buy-policy" className="btn btn-primary">Buy Your First Policy</a>
                </div>
            ) : (
                <div className="policies-table-container card fade-in">
                    <table className="policies-table">
                        <thead>
                            <tr>
                                <th>Policy Name</th>
                                <th>Company</th>
                                <th>Premium</th>
                                <th>Coverage</th>
                                <th>Start Date</th>
                                <th>End Date</th>
                                <th>Status</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {policies.map((policy) => (
                                <tr key={policy.id}>
                                    <td>{policy.policyName}</td>
                                    <td>{policy.companyName}</td>
                                    <td>${policy.premiumAmount.toLocaleString()}</td>
                                    <td>${policy.coverageAmount.toLocaleString()}</td>
                                    <td>{new Date(policy.startDate).toLocaleDateString()}</td>
                                    <td>{new Date(policy.endDate).toLocaleDateString()}</td>
                                    <td>
                                        <span className={`badge badge-${policy.status.toLowerCase()}`}>
                                            {policy.status}
                                        </span>
                                    </td>
                                    <td>
                                        {policy.status === 'ACTIVE' && (
                                            <button
                                                onClick={() => handleRenew(policy.id)}
                                                className="btn btn-sm btn-secondary"
                                            >
                                                Renew
                                            </button>
                                        )}
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            )}
        </div>
    );
};

export default MyPolicies;
