// frontend-angular/src/app/features/client/profile/profile.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { UserService } from '../../../core/services/user.service';
import { AuthService } from '../../../core/services/auth.service';

@Component({
  selector: 'app-profile',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.css']
})
export class ProfileComponent implements OnInit {

  userId!: number;

  // ===== FORMS =====
  profileForm!: FormGroup;
  passwordForm!: FormGroup;

  // ===== STATE =====
  loading = true;
  profileSuccess = '';
  profileError = '';
  passwordSuccess = '';
  passwordError = '';

  constructor(
    private fb: FormBuilder,
    private userService: UserService,
    private authService: AuthService
  ) {}

ngOnInit(): void {
  this.initForms();

  // 🔥 DIRECT BACKEND CALL – single source of truth
  this.userService.getCurrentUser().subscribe({
    next: (user: any) => {
      console.log('BACKEND USER =>', user);

      this.userId = Number(user.id);

      this.profileForm.patchValue({
        firstName: user.firstName,
        lastName: user.lastName,
        email: user.email
      });

      this.loading = false;
    },
    error: (err) => {
      console.error('CURRENT USER ERROR', err);
      this.profileError = 'Failed to load user profile';
      this.loading = false;
    }
  });
}


  // =========================
  // INIT FORMS
  // =========================
  initForms(): void {
    this.profileForm = this.fb.group({
      firstName: ['', Validators.required],
      lastName: ['', Validators.required],
      email: ['', [Validators.required, Validators.email]]
    });

    this.passwordForm = this.fb.group({
      currentPassword: ['', Validators.required],
      newPassword: ['', Validators.required],
      confirmNewPassword: ['', Validators.required]
    });
  }

  // =========================
  // FETCH PROFILE
  // =========================
fetchProfile(): void {
  this.userService.getProfile(this.userId).subscribe({
    next: (data: any) => {
      this.profileForm.patchValue({
        firstName: data.firstName,
        lastName: data.lastName,
        email: data.email
      });
      this.loading = false;
    },
    error: (err) => {
      console.error('PROFILE LOAD ERROR', err);
      this.profileError = 'Failed to load profile';
      this.loading = false;
    }
  });
}





  // =========================
  // UPDATE PROFILE
  // =========================
onProfileSubmit(): void {
  if (this.profileForm.invalid) return;

  console.log('UPDATING PROFILE FOR USER ID =>', this.userId);

  this.userService
    .updateProfile(this.userId, this.profileForm.value)
    .subscribe({
      next: (updatedUser: any) => {
        const existingUser = this.authService.getUser();

        this.authService.setUser({
          ...existingUser,
          firstName: updatedUser.firstName,
          lastName: updatedUser.lastName,
          email: updatedUser.email
        });

        this.profileSuccess = 'Profile updated successfully!';
      },
      error: (err) => {
        console.error('UPDATE ERROR', err);
        this.profileError = err.error?.error || 'Profile update failed';
      }
    });
}



  // =========================
  // CHANGE PASSWORD
  // =========================
 onPasswordSubmit(): void {
  if (this.passwordForm.invalid) return;

  const { newPassword, confirmNewPassword } = this.passwordForm.value;

  if (newPassword !== confirmNewPassword) {
    this.passwordError = 'New passwords do not match';
    return;
  }

  console.log('CHANGING PASSWORD FOR USER ID =>', this.userId);

  this.userService
    .changePassword(this.userId, this.passwordForm.value)
    .subscribe({
      next: () => {
        this.passwordSuccess = 'Password changed successfully!';
        this.passwordForm.reset();
      },
      error: (err) => {
        console.error('PASSWORD ERROR', err);
        this.passwordError = err.error?.error || 'Password change failed';
      }
    });
}


}
<div class="auth-container">


  <div class="profile-container">

    <!-- ================= PROFILE UPDATE ================= -->
    <div class="auth-card card fade-in">
      <h2>Update Profile</h2>

      <form [formGroup]="profileForm" (ngSubmit)="onProfileSubmit()" class="auth-form">

        <div *ngIf="profileSuccess" class="success-message">
          {{ profileSuccess }}
        </div>

        <div *ngIf="profileError" class="error-message">
          {{ profileError }}
        </div>

        <div class="input-row">
          <div class="input-group">
            <label class="input-label">First Name</label>
            <input type="text" formControlName="firstName" class="input-field" />
          </div>

          <div class="input-group">
            <label class="input-label">Last Name</label>
            <input type="text" formControlName="lastName" class="input-field" />
          </div>
        </div>

        <div class="input-group">
          <label class="input-label">Email</label>
          <input type="email" formControlName="email" class="input-field" />
        </div>

        <button type="submit" class="btn btn-primary">
          Update Profile
        </button>
      </form>
    </div>

    <!-- ================= PASSWORD CHANGE ================= -->
    <div class="auth-card card fade-in">
      <h2>Change Password</h2>

      <form [formGroup]="passwordForm" (ngSubmit)="onPasswordSubmit()" class="auth-form">

        <div *ngIf="passwordSuccess" class="success-message">
          {{ passwordSuccess }}
        </div>

        <div *ngIf="passwordError" class="error-message">
          {{ passwordError }}
        </div>

        <div class="input-group">
          <label class="input-label">Current Password</label>
          <input type="password" formControlName="currentPassword" class="input-field" />
        </div>

        <div class="input-group">
          <label class="input-label">New Password</label>
          <input type="password" formControlName="newPassword" class="input-field" />
        </div>

        <div class="input-group">
          <label class="input-label">Confirm New Password</label>
          <input type="password" formControlName="confirmNewPassword" class="input-field" />
        </div>

        <button type="submit" class="btn btn-primary">
          Change Password
        </button>
      </form>
    </div>

  </div>
</div>

// frontend/src/pages/Client/Profile.jsx
import { useState, useEffect } from 'react';
import { userService } from '../../services';
import '../Auth/Auth.css';

const Profile = () => {
    const [profile, setProfile] = useState({
        firstName: '',
        lastName: '',
        email: '',
    });
    const [passwordData, setPasswordData] = useState({
        currentPassword: '',
        newPassword: '',
        confirmNewPassword: '',
    });
    const [loading, setLoading] = useState(true);
    const [profileError, setProfileError] = useState('');
    const [passwordError, setPasswordError] = useState('');
    const [profileSuccess, setProfileSuccess] = useState('');
    const [passwordSuccess, setPasswordSuccess] = useState('');

    useEffect(() => {
        fetchProfile();
    }, []);

    const fetchProfile = async () => {
        try {
            const data = await userService.getProfile();
            setProfile({
                firstName: data.firstName,
                lastName: data.lastName,
                email: data.email,
            });
        } catch (error) {
            setProfileError('Failed to load profile');
        } finally {
            setLoading(false);
        }
    };

    const handleProfileChange = (e) => {
        setProfile({ ...profile, [e.target.name]: e.target.value });
        setProfileError('');
        setProfileSuccess('');
    };

    const handlePasswordChange = (e) => {
        setPasswordData({ ...passwordData, [e.target.name]: e.target.value });
        setPasswordError('');
        setPasswordSuccess('');
    };

    const handleProfileSubmit = async (e) => {
        e.preventDefault();
        try {
            await userService.updateProfile(profile);
            setProfileSuccess('Profile updated successfully!');
        } catch (error) {
            setProfileError(error.response?.data?.error || 'Failed to update profile');
        }
    };

    const handlePasswordSubmit = async (e) => {
        e.preventDefault();
        setPasswordError('');

        if (passwordData.newPassword !== passwordData.confirmNewPassword) {
            setPasswordError('New passwords do not match');
            return;
        }

        try {
            await userService.changePassword({
                currentPassword: passwordData.currentPassword,
                newPassword: passwordData.newPassword,
            });
            setPasswordSuccess('Password changed successfully!');
            setPasswordData({
                currentPassword: '',
                newPassword: '',
                confirmNewPassword: '',
            });
        } catch (error) {
            setPasswordError(error.response?.data?.error || 'Failed to change password');
        }
    };

    if (loading) {
        return <div className="loading"><div className="spinner"></div></div>;
    }

    return (
        <div className="auth-container">
            <div className="profile-container">
                {/* Profile Update Section */}
                <div className="auth-card card fade-in">
                    <h2>Update Profile</h2>
                    <form onSubmit={handleProfileSubmit} className="auth-form">
                        {/* {profileError && <div className="error-message">{profileError}</div>} */}
                        {profileSuccess && <div className="success-message">{profileSuccess}</div>}

                        <div className="input-row">
                            <div className="input-group">
                                <label className="input-label">First Name</label>
                                <input
                                    type="text"
                                    name="firstName"
                                    value={profile.firstName}
                                    onChange={handleProfileChange}
                                    className="input-field"
                                    required
                                />
                            </div>

                            <div className="input-group">
                                <label className="input-label">Last Name</label>
                                <input
                                    type="text"
                                    name="lastName"
                                    value={profile.lastName}
                                    onChange={handleProfileChange}
                                    className="input-field"
                                    required
                                />
                            </div>
                        </div>

                        <div className="input-group">
                            <label className="input-label">Email</label>
                            <input
                                type="email"
                                name="email"
                                value={profile.email}
                                onChange={handleProfileChange}
                                className="input-field"
                                required
                            />
                        </div>

                        <button type="submit" className="btn btn-primary">
                            Update Profile
                        </button>
                    </form>
                </div>

                {/* Password Change Section */}
                <div className="auth-card card fade-in">
                    <h2>Change Password</h2>
                    <form onSubmit={handlePasswordSubmit} className="auth-form">
                        {passwordError && <div className="error-message">{passwordError}</div>}
                        {passwordSuccess && <div className="success-message">{passwordSuccess}</div>}

                        <div className="input-group">
                            <label className="input-label">Current Password</label>
                            <input
                                type="password"
                                name="currentPassword"
                                value={passwordData.currentPassword}
                                onChange={handlePasswordChange}
                                className="input-field"
                                required
                            />
                        </div>

                        <div className="input-group">
                            <label className="input-label">New Password</label>
                            <input
                                type="password"
                                name="newPassword"
                                value={passwordData.newPassword}
                                onChange={handlePasswordChange}
                                className="input-field"
                                required
                            />
                        </div>

                        <div className="input-group">
                            <label className="input-label">Confirm New Password</label>
                            <input
                                type="password"
                                name="confirmNewPassword"
                                value={passwordData.confirmNewPassword}
                                onChange={handlePasswordChange}
                                className="input-field"
                                required
                            />
                        </div>

                        <button type="submit" className="btn btn-primary">
                            Change Password
                        </button>
                    </form>
                </div>
            </div>
        </div>
    );
};

export default Profile;
