// frontend/src/pages/Auth/Login.jsx
import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { authService } from '../../services';
import './Auth.css';

const Login = () => {
    const [formData, setFormData] = useState({
        email: '',
        password: '',
    });
    const [error, setError] = useState('');
    const [loading, setLoading] = useState(false);
    const [touched, setTouched] = useState({ email: false, password: false });
    const { login } = useAuth();
    const navigate = useNavigate();

    const validateEmail = (email) => {
        return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
    };
    const isEmailValid = validateEmail(formData.email);
    const isPasswordValid = formData.password.length >= 6;

    const handleChange = (e) => {
        setFormData({
            ...formData,
            [e.target.name]: e.target.value,
        });
        setError('');
    };
    const handleBlur = (e) => {
        setTouched({ ...touched, [e.target.name]: true });
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        setLoading(true);
        setError('');

        if (!isEmailValid || !isPasswordValid) {
            setLoading(false);
            return;
        }

        try {
            const response = await authService.login(formData);
            login(response);

            // Redirect based on role
            if (response.role === 'CLIENT') {
                navigate('/client');
            } else if (response.role === 'ADMIN') {
                navigate('/admin');
            }
        } catch (err) {
            setError(err.response?.data?.error || 'Login failed. Please try again.');
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="auth-container">
            
                <div className="auth-card card">
                    <div className="rounded-2xl bg-gradient-to-br from-indigo-500 via-indigo-600 to-blue-600 p-8 text-white">
                        <p className="text-xs uppercase tracking-[0.3em] text-indigo-200">
                            InsurAI
                        </p>
                        <h2 className="mt-6 text-3xl font-semibold leading-tight">
                            Corporate Policy Automation System
                        </h2>
                        <p className="mt-4 text-sm text-indigo-100">
                            Securely create, validate, and manage AI-assisted policies in one
                            corporate-grade workspace.
                        </p>
                        <ul className="mt-10 space-y-4 text-sm text-indigo-50">
                            <li> AI-generated drafts tailored for enterprises.</li>
                            <li> Compliance insights and renewal tracking.</li>
                            <li> Encrypted JWT authentication, Bcrypt passwords and secure uploads.</li>
                        </ul>
                    </div>
                    </div>
                    
                    <div className="auth-card card">
                        <div className="auth-header">
                            <h1>Welcome Back</h1>
                            <p>Sign in to your Insurai account</p>
                        </div>

                        <form onSubmit={handleSubmit} className="auth-form">
                            {error && <div className="error-message">{error}</div>}

                            <div className="input-group">
                                <label className="input-label">Email</label>
                                <input
                                    type="email"
                                    name="email"
                                    value={formData.email}
                                    onChange={handleChange}
                                    onBlur={handleBlur}
                                    aria-invalid={touched.email && !isEmailValid}
                                    aria-describedby="email-error"
                                    className={`input-field ${touched.email ? (isEmailValid ? 'valid' : 'invalid') : ''}`}
                                    placeholder="you@example.com"
                                    required
                                />
                                {touched.email && !isEmailValid && (
                                    <div id="email-error" className="error-message">Enter a valid email address</div>
                                )}
                            </div>

                            <div className="input-group">
                                <label className="input-label">Password</label>
                                <input
                                    type="password"
                                    name="password"
                                    value={formData.password}
                                    onChange={handleChange}
                                    onBlur={handleBlur}
                                    aria-invalid={touched.password && !isPasswordValid}
                                    aria-describedby="password-error"
                                    className={`input-field ${touched.password ? (isPasswordValid ? 'valid' : 'invalid') : ''}`}
                                    placeholder="••••••••"
                                    required
                                />
                                {touched.password && !isPasswordValid && (
                                    <div id="password-error" className="error-message">Minimum 6 characters</div>
                                )}
                            </div>

                            <button type="submit" className="btn btn-primary auth-btn" disabled={loading}>
                                {loading ? 'Signing in...' : 'Sign In'}
                            </button>
                        </form>

                        <div className="auth-footer">
                            <p>
                                Don't have an account? <Link to="/signup">Sign up</Link>
                            </p>
                        </div>
                    </div>
                </div>
                );
};

                export default Login;

// frontend-angular/src/app/features/auth/login/login.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';

@Component({
    selector: 'app-login',
    standalone: true,
    imports: [CommonModule, ReactiveFormsModule, RouterModule],
    templateUrl: './login.component.html',
    styleUrls: ['./login.component.scss']
})
export class LoginComponent {
    loginForm: FormGroup;
    error = '';
    loading = false;

    constructor(
        private fb: FormBuilder,
        private authService: AuthService,
        private router: Router
    ) {
        this.loginForm = this.fb.group({
            email: ['', [Validators.required, Validators.email]],
            password: ['', [Validators.required, Validators.minLength(6)]]
        });
    }

    get email() {
        return this.loginForm.get('email');
    }

    get password() {
        return this.loginForm.get('password');
    }

    onSubmit(): void {
        if (this.loginForm.invalid) {
            this.loginForm.markAllAsTouched();
            return;
        }

        this.loading = true;
        this.error = '';

        this.authService.login(this.loginForm.value).subscribe({
            next: (response) => {
                // Redirect based on role
                if (response.role === 'CLIENT') {
                    this.router.navigate(['/client']);
                } else if (response.role === 'ADMIN') {
                    this.router.navigate(['/admin']);
                }
            },
            error: (err) => {
                this.error = err.error?.error || 'Login failed. Please try again.';
                this.loading = false;
            }
        });
    }
}

<div class="auth-container">
    <div class="auth-card card">
        <div class="rounded-2xl bg-gradient-to-br from-indigo-500 via-indigo-600 to-blue-600 p-8 text-white">
            <p class="text-xs uppercase tracking-[0.3em] text-indigo-200">
                InsurAI
            </p>
            <h2 class="mt-6 text-3xl font-semibold leading-tight">
                Corporate Policy Automation System
            </h2>
            <p class="mt-4 text-sm text-indigo-100">
                Securely create, validate, and manage AI-assisted policies in one
                corporate-grade workspace.
            </p>
            <ul class="mt-10 space-y-4 text-sm text-indigo-50">
                <li>AI-generated drafts tailored for enterprises.</li>
                <li>Compliance insights and renewal tracking.</li>
                <li>Encrypted JWT authentication, Bcrypt passwords and secure uploads.</li>
            </ul>
        </div>
    </div>

    <div class="auth-card card">
        <div class="auth-header">
            <h1>Welcome Back</h1>
            <p>Sign in to your Insurai account</p>
        </div>

        <form [formGroup]="loginForm" (ngSubmit)="onSubmit()" class="auth-form">
            <div *ngIf="error" class="error-message">{{ error }}</div>

            <div class="input-group">
                <label class="input-label">Email</label>
                <input type="email" formControlName="email" [class.invalid]="email?.invalid && email?.touched"
                    [class.valid]="email?.valid && email?.touched" class="input-field" placeholder="you@example.com" />
                <div *ngIf="email?.invalid && email?.touched" class="error-message">
                    <span *ngIf="email?.errors?.['required']">Email is required</span>
                    <span *ngIf="email?.errors?.['email']">Enter a valid email address</span>
                </div>
            </div>

            <div class="input-group">
                <label class="input-label">Password</label>
                <input type="password" formControlName="password"
                    [class.invalid]="password?.invalid && password?.touched"
                    [class.valid]="password?.valid && password?.touched" class="input-field" placeholder="••••••••" />
                <div *ngIf="password?.invalid && password?.touched" class="error-message">
                    <span *ngIf="password?.errors?.['required']">Password is required</span>
                    <span *ngIf="password?.errors?.['minlength']">Minimum 6 characters</span>
                </div>
            </div>

            <button type="submit" class="btn btn-primary auth-btn" [disabled]="loading">
                {{ loading ? 'Signing in...' : 'Sign In' }}
            </button>
        </form>

        <div class="auth-footer">
            <p>
                Don't have an account? <a routerLink="/signup">Sign up</a>
            </p>
        </div>
    </div>
</div>
