// frontend/src/pages/Client/ClaimPolicies.jsx
import { useState, useEffect } from 'react';
import { clientPolicyService, claimService } from '../../services';
import './ClaimPolicies.css';

const ClaimPolicies = () => {
    const [policies, setPolicies] = useState([]);
    const [formData, setFormData] = useState({
        clientPolicyId: '',
        claimAmountRequested: '',
        description: '',
    });
    const [documents, setDocuments] = useState([]);
    const [selectedPolicy, setSelectedPolicy] = useState(null);
    const [loading, setLoading] = useState(true);
    const [submitting, setSubmitting] = useState(false);
    const [error, setError] = useState('');
    const [success, setSuccess] = useState(false);

    useEffect(() => {
        const fetchPolicies = async () => {
            try {
                const data = await clientPolicyService.getMyPolicies();
                setPolicies(data.filter(p => p.status === 'ACTIVE'));
            } catch (err) {
                setError('Failed to load policies');
            } finally {
                setLoading(false);
            }
        };
        fetchPolicies();
    }, []);

    const handlePolicySelect = (e) => {
        const policyId = e.target.value;
        setFormData({ ...formData, clientPolicyId: policyId });
        const policy = policies.find(p => p.id === parseInt(policyId));
        setSelectedPolicy(policy);
    };

    const handleChange = (e) => {
        setFormData({ ...formData, [e.target.name]: e.target.value });
    };

    const handleFileChange = (e) => {
        setDocuments(Array.from(e.target.files));
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        setSubmitting(true);
        setError('');

        try {
            await claimService.createClaim({ ...formData, documents });
            setSuccess(true);
        } catch (err) {
            setError(err.response?.data?.error || 'Failed to submit claim');
        } finally {
            setSubmitting(false);
        }
    };

    if (loading) {
        return <div className="loading"><div className="spinner"></div></div>;
    }

    if (success) {
        return (
            <div className="success-container container">
                <div className="success-card card fade-in">
                    <div className="success-icon">✅</div>
                    <h1>Claim Submitted Successfully!</h1>
                    <p>Your claim has been submitted and is under review.</p>
                    <div className="success-actions">
                        <a href="/client" className="btn btn-primary">Go to Dashboard</a>
                        <a href="/client/my-policies" className="btn btn-secondary">View My Policies</a>
                    </div>
                </div>
            </div>
        );
    }

    return (
        <div className="claim-policies-container container">
            <h1 className="page-title fade-in">File Insurance Claim</h1>

            {policies.length === 0 ? (
                <div className="empty-state card">
                    <p>You don't have any active policies to claim against.</p>
                    <a href="/client/buy-policy" className="btn btn-primary">Buy a Policy</a>
                </div>
            ) : (
                <form onSubmit={handleSubmit} className="claim-form card fade-in">
                    {error && <div className="error-message">{error}</div>}

                    <div className="input-group">
                        <label className="input-label">Select Policy</label>
                        <select
                            name="clientPolicyId"
                            value={formData.clientPolicyId}
                            onChange={handlePolicySelect}
                            className="input-field"
                            required
                        >
                            <option value="">-- Select a Policy --</option>
                            {policies.map(policy => (
                                <option key={policy.id} value={policy.id}>
                                    {policy.policyName} - {policy.companyName}
                                </option>
                            ))}
                        </select>
                    </div>

                    {selectedPolicy && (
                        <div className="policy-info">
                            <p><strong>Max Coverage:</strong> ${selectedPolicy.coverageAmount.toLocaleString()}</p>
                        </div>
                    )}

                    <div className="input-group">
                        <label className="input-label">Claim Amount Requested</label>
                        <input
                            type="number"
                            name="claimAmountRequested"
                            value={formData.claimAmountRequested}
                            onChange={handleChange}
                            className="input-field"
                            placeholder="Enter amount"
                            min="0"
                            max={selectedPolicy?.coverageAmount}
                            required
                        />
                    </div>

                    <div className="input-group">
                        <label className="input-label">Description of Incident</label>
                        <textarea
                            name="description"
                            value={formData.description}
                            onChange={handleChange}
                            className="input-field"
                            rows="5"
                            placeholder="Describe the incident and reason for claim..."
                            required
                        />
                    </div>

                    <div className="input-group">
                        <label className="input-label">Supporting Documents</label>
                        <input
                            type="file"
                            onChange={handleFileChange}
                            className="input-field"
                            multiple
                            accept=".pdf,.jpg,.jpeg,.png"
                        />
                        <small className="input-hint">Upload supporting documents (PDF, JPG, PNG)</small>
                    </div>

                    <button type="submit" className="btn btn-primary" disabled={submitting}>
                        {submitting ? 'Submitting Claim...' : 'Submit Claim'}
                    </button>
                </form>
            )}
        </div>
    );
};

export default ClaimPolicies;

// frontend-angular/src/app/features/client/claim-policies/claim-policies.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { ClientPolicyService } from '../../../core/services/client-policy.service';
import { ClaimService } from '../../../core/services/claim.service';

@Component({
  selector: 'app-claim-policies',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterModule],
  template: `
    <div class="container" style="padding: 2rem; max-width: 800px; margin: 0 auto;">
      <h1>File a Claim</h1>
      <form [formGroup]="claimForm" (ngSubmit)="onSubmit()" class="card" style="padding: 2rem; margin-top: 2rem;">
        <div *ngIf="error" class="error-message">{{ error }}</div>
        <div *ngIf="success" class="success-message">Claim submitted successfully!</div>
        
        <div class="input-group">
          <label class="input-label">Select Policy</label>
          <select formControlName="clientPolicyId" class="input-field">
            <option value="">Choose a policy...</option>
            <option *ngFor="let policy of policies" [value]="policy.id">
              {{ policy.policy?.name }} - {{ policy.companyName }}
            </option>
          </select>
        </div>

        <div class="input-group">
          <label class="input-label">Claim Amount</label>
          <input type="number" formControlName="claimAmountRequested" class="input-field" />
        </div>

        <div class="input-group">
          <label class="input-label">Description</label>
          <textarea formControlName="description" class="input-field" rows="4"></textarea>
        </div>

        <button type="submit" class="btn btn-primary" [disabled]="loading || claimForm.invalid">
          {{ loading ? 'Submitting...' : 'Submit Claim' }}
        </button>
      </form>
    </div>
  `,
  styles: []
})
export class ClaimPoliciesComponent {
  claimForm: FormGroup;
  policies: any[] = [];
  loading = false;
  error = '';
  success = false;

  constructor(
    private fb: FormBuilder,
    private clientPolicyService: ClientPolicyService,
    private claimService: ClaimService
  ) {
    this.claimForm = this.fb.group({
      clientPolicyId: ['', Validators.required],
      claimAmountRequested: ['', [Validators.required, Validators.min(1)]],
      description: ['', Validators.required]
    });

    this.clientPolicyService.getMyPolicies().subscribe({
      next: (data) => this.policies = data
    });
  }

  onSubmit(): void {
    if (this.claimForm.invalid) return;
    this.loading = true;
    this.error = '';

    this.claimService.createClaim(this.claimForm.value).subscribe({
      next: () => {
        this.success = true;
        this.loading = false;
        this.claimForm.reset();
      },
      error: (err) => {
        this.error = err.error?.error || 'Failed to submit claim';
        this.loading = false;
      }
    });
  }
}
