// frontend/src/pages/Auth/Signup.jsx
import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { authService } from '../../services';
import './Auth.css';

const Signup = () => {
    const [formData, setFormData] = useState({
        firstName: '',
        lastName: '',
        email: '',
        password: '',
        confirmPassword: '',
    });
    const [error, setError] = useState('');
    const [loading, setLoading] = useState(false);
    const { login } = useAuth();
    const navigate = useNavigate();

    const handleChange = (e) => {
        setFormData({
            ...formData,
            [e.target.name]: e.target.value,
        });
        setError('');
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        setError('');

        // Validate password match
        if (formData.password !== formData.confirmPassword) {
            setError('Passwords do not match');
            return;
        }

        if (formData.password.length < 6) {
            setError('Password must be at least 6 characters');
            return;
        }

        setLoading(true);

        try {
            const { confirmPassword, ...signupData } = formData;
            const response = await authService.signup(signupData);
            login(response);
            navigate('/client'); // New users are always clients
        } catch (err) {
            setError(err.response?.data?.error || 'Signup failed. Please try again.');
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="auth-container">

            <div className="auth-card card">
                <div className="rounded-2xl bg-gradient-to-br from-indigo-500 via-indigo-600 to-blue-600 p-8 text-white">
                    <p className="text-xs uppercase tracking-[0.3em] text-indigo-200">
                        InsurAI
                    </p>
                    <h2 className="mt-6 text-3xl font-semibold leading-tight">
                        Corporate Policy Automation System
                    </h2>
                    <p className="mt-4 text-sm text-indigo-100">
                        Securely create, validate, and manage AI-assisted policies in one
                        corporate-grade workspace.
                    </p>
                    <ul className="mt-10 space-y-4 text-sm text-indigo-50">
                        <li> AI-generated drafts tailored for enterprises.</li>
                        <li> Compliance insights and renewal tracking.</li>
                        <li> Encrypted JWT authentication, Bcrypt passwords and secure uploads.</li>
                    </ul>
                </div>
            </div>

            <div className="auth-card card fade-in">
                <div className="auth-header">
                    <h1>Create Account</h1>
                    <p>Join Insurai and protect your business</p>
                </div>

                <form onSubmit={handleSubmit} className="auth-form">
                    {error && <div className="error-message">{error}</div>}

                    <div className="input-row">
                        <div className="input-group">
                            <label className="input-label">First Name</label>
                            <input
                                type="text"
                                name="firstName"
                                value={formData.firstName}
                                onChange={handleChange}
                                className="input-field"
                                placeholder="John"
                                required
                            />
                        </div>

                        <div className="input-group">
                            <label className="input-label">Last Name</label>
                            <input
                                type="text"
                                name="lastName"
                                value={formData.lastName}
                                onChange={handleChange}
                                className="input-field"
                                placeholder="Doe"
                                required
                            />
                        </div>
                    </div>

                    <div className="input-group">
                        <label className="input-label">Email</label>
                        <input
                            type="email"
                            name="email"
                            value={formData.email}
                            onChange={handleChange}
                            className="input-field"
                            placeholder="you@company.com"
                            required
                        />
                    </div>

                    <div className="input-group">
                        <label className="input-label">Password</label>
                        <input
                            type="password"
                            name="password"
                            value={formData.password}
                            onChange={handleChange}
                            className="input-field"
                            placeholder="••••••••"
                            required
                        />
                    </div>

                    <div className="input-group">
                        <label className="input-label">Confirm Password</label>
                        <input
                            type="password"
                            name="confirmPassword"
                            value={formData.confirmPassword}
                            onChange={handleChange}
                            className="input-field"
                            placeholder="••••••••"
                            required
                        />
                    </div>

                    <button type="submit" className="btn btn-primary auth-btn" disabled={loading}>
                        {loading ? 'Creating account...' : 'Sign Up'}
                    </button>
                </form>

                <div className="auth-footer">
                    <p>
                        Already have an account? <Link to="/login">Sign in</Link>
                    </p>
                </div>
            </div>
        </div>
    );
};

export default Signup;

// frontend-angular/src/app/features/auth/signup/signup.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule, AbstractControl, ValidationErrors } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';

@Component({
    selector: 'app-signup',
    standalone: true,
    imports: [CommonModule, ReactiveFormsModule, RouterModule],
    templateUrl: './signup.component.html',
    styleUrls: ['./signup.component.scss']
})
export class SignupComponent {
    signupForm: FormGroup;
    error = '';
    loading = false;

    constructor(
        private fb: FormBuilder,
        private authService: AuthService,
        private router: Router
    ) {
        this.signupForm = this.fb.group({
            firstName: ['', [Validators.required]],
            lastName: ['', [Validators.required]],
            email: ['', [Validators.required, Validators.email]],
            password: ['', [Validators.required, Validators.minLength(6)]],
            confirmPassword: ['', [Validators.required]]
        }, { validators: this.passwordMatchValidator });
    }

    passwordMatchValidator(control: AbstractControl): ValidationErrors | null {
        const password = control.get('password');
        const confirmPassword = control.get('confirmPassword');

        if (!password || !confirmPassword) {
            return null;
        }

        return password.value === confirmPassword.value ? null : { passwordMismatch: true };
    }

    get firstName() {
        return this.signupForm.get('firstName');
    }

    get lastName() {
        return this.signupForm.get('lastName');
    }

    get email() {
        return this.signupForm.get('email');
    }

    get password() {
        return this.signupForm.get('password');
    }

    get confirmPassword() {
        return this.signupForm.get('confirmPassword');
    }

    onSubmit(): void {
        if (this.signupForm.invalid) {
            this.signupForm.markAllAsTouched();
            return;
        }

        this.loading = true;
        this.error = '';

        const { confirmPassword, ...signupData } = this.signupForm.value;

        this.authService.signup(signupData).subscribe({
            next: () => {
                this.router.navigate(['/client']); // New users are always clients
            },
            error: (err) => {
                this.error = err.error?.error || 'Signup failed. Please try again.';
                this.loading = false;
            }
        });
    }
}

<div class="auth-container">
    <div class="auth-card card">
        <div class="rounded-2xl bg-gradient-to-br from-indigo-500 via-indigo-600 to-blue-600 p-8 text-white">
            <p class="text-xs uppercase tracking-[0.3em] text-indigo-200">
                InsurAI
            </p>
            <h2 class="mt-6 text-3xl font-semibold leading-tight">
                Corporate Policy Automation System
            </h2>
            <p class="mt-4 text-sm text-indigo-100">
                Securely create, validate, and manage AI-assisted policies in one
                corporate-grade workspace.
            </p>
            <ul class="mt-10 space-y-4 text-sm text-indigo-50">
                <li>AI-generated drafts tailored for enterprises.</li>
                <li>Compliance insights and renewal tracking.</li>
                <li>Encrypted JWT authentication, Bcrypt passwords and secure uploads.</li>
            </ul>
        </div>
    </div>

    <div class="auth-card card fade-in">
        <div class="auth-header">
            <h1>Create Account</h1>
            <p>Join Insurai and protect your business</p>
        </div>

        <form [formGroup]="signupForm" (ngSubmit)="onSubmit()" class="auth-form">
            <div *ngIf="error" class="error-message">{{ error }}</div>

            <div class="input-row">
                <div class="input-group">
                    <label class="input-label">First Name</label>
                    <input type="text" formControlName="firstName"
                        [class.invalid]="firstName?.invalid && firstName?.touched"
                        [class.valid]="firstName?.valid && firstName?.touched" class="input-field" placeholder="John" />
                    <div *ngIf="firstName?.invalid && firstName?.touched" class="error-message">
                        First name is required
                    </div>
                </div>

                <div class="input-group">
                    <label class="input-label">Last Name</label>
                    <input type="text" formControlName="lastName"
                        [class.invalid]="lastName?.invalid && lastName?.touched"
                        [class.valid]="lastName?.valid && lastName?.touched" class="input-field" placeholder="Doe" />
                    <div *ngIf="lastName?.invalid && lastName?.touched" class="error-message">
                        Last name is required
                    </div>
                </div>
            </div>

            <div class="input-group">
                <label class="input-label">Email</label>
                <input type="email" formControlName="email" [class.invalid]="email?.invalid && email?.touched"
                    [class.valid]="email?.valid && email?.touched" class="input-field" placeholder="you@company.com" />
                <div *ngIf="email?.invalid && email?.touched" class="error-message">
                    <span *ngIf="email?.errors?.['required']">Email is required</span>
                    <span *ngIf="email?.errors?.['email']">Enter a valid email address</span>
                </div>
            </div>

            <div class="input-group">
                <label class="input-label">Password</label>
                <input type="password" formControlName="password"
                    [class.invalid]="password?.invalid && password?.touched"
                    [class.valid]="password?.valid && password?.touched" class="input-field" placeholder="••••••••" />
                <div *ngIf="password?.invalid && password?.touched" class="error-message">
                    <span *ngIf="password?.errors?.['required']">Password is required</span>
                    <span *ngIf="password?.errors?.['minlength']">Minimum 6 characters</span>
                </div>
            </div>

            <div class="input-group">
                <label class="input-label">Confirm Password</label>
                <input type="password" formControlName="confirmPassword"
                    [class.invalid]="(confirmPassword?.invalid || signupForm.errors?.['passwordMismatch']) && confirmPassword?.touched"
                    [class.valid]="confirmPassword?.valid && !signupForm.errors?.['passwordMismatch'] && confirmPassword?.touched"
                    class="input-field" placeholder="••••••••" />
                <div *ngIf="confirmPassword?.touched && signupForm.errors?.['passwordMismatch']" class="error-message">
                    Passwords must match
                </div>
            </div>

            <button type="submit" class="btn btn-primary auth-btn" [disabled]="loading">
                {{ loading ? 'Creating account...' : 'Sign Up' }}
            </button>
        </form>

        <div class="auth-footer">
            <p>
                Already have an account? <a routerLink="/login">Sign in</a>
            </p>
        </div>
    </div>
</div>
