// frontend/src/pages/Client/ClientDashboard.jsx
import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { clientPolicyService, claimService } from '../../services';
import './ClientDashboard.css';
import { useNavigate } from "react-router-dom";
const ClientDashboard = () => {
    const [stats, setStats] = useState({
        totalPolicies: 0,
        activePolicies: 0,
        pendingClaims: 0,
    });
    const [loading, setLoading] = useState(true);
const navigate = useNavigate();
    useEffect(() => {
        const fetchStats = async () => {
            try {
                const [policies, claims] = await Promise.all([
                    clientPolicyService.getMyPolicies(),
                    claimService.getMyClaims(),
                ]);

                setStats({
                    totalPolicies: policies.length,
                    activePolicies: policies.filter(p => p.status === 'ACTIVE').length,
                    pendingClaims: claims.filter(c => c.status === 'PENDING').length,
                });
            } catch (error) {
                console.error('Error fetching stats:', error);
            } finally {
                setLoading(false);
            }
        };

        fetchStats();
    }, []);

    if (loading) {
        return <div className="loading"><div className="spinner"></div></div>;
    }

    return (
        <div className="dashboard-container container">
            <div className="dashboard-header fade-in">
                <h1>Client Dashboard</h1>
                <p>Manage your insurance policies and claims</p>
            </div>

            <div className="stats-grid fade-in">
                <div className="stat-card card">
                    <div className="stat-icon">📋</div>
                    <div className="stat-content">
                        <h3>{stats.totalPolicies}</h3>
                        <p>Total Policies</p>
                    </div>
                </div>

                <div className="stat-card card">
                    <div className="stat-icon">✅</div>
                    <div className="stat-content">
                        <h3>{stats.activePolicies}</h3>
                        <p>Active Policies</p>
                    </div>
                </div>

                <div className="stat-card card">
                    <div className="stat-icon">⏳</div>
                    <div className="stat-content">
                        <h3>{stats.pendingClaims}</h3>
                        <p>Pending Claims</p>
                    </div>
                </div>
            </div>

            <div className="quick-actions fade-in">
                <h2>Quick Actions</h2>
                <div className="actions-grid">
                    <Link to="/client/buy-policy" className="action-card card card-hover">
                        <div className="action-icon">🛒</div>
                        <h3>Buy New Policy</h3>
                        <p>Browse and purchase insurance policies</p>
                    </Link>

                    <Link to="/client/my-policies" className="action-card card card-hover">
                        <div className="action-icon">📄</div>
                        <h3>My Policies</h3>
                        <p>View and manage your policies</p>
                    </Link>

                    <Link to="/client/claim" className="action-card card card-hover">
                        <div className="action-icon">📝</div>
                        <h3>File a Claim</h3>
                        <p>Submit a new insurance claim</p>
                    </Link>

                    <Link to="/client/profile" className="action-card card card-hover">
                        <div className="action-icon">👤</div>
                        <h3>Profile Settings</h3>
                        <p>Update your account information</p>
                    </Link>
                </div>
            </div>
             <button
  className="ai-fab"
  onClick={() => navigate("/client/corporate-ai")}
  title="Corporate AI Assistant"
>
  🤖
</button>
        </div>
    );
};

export default ClientDashboard;

// frontend-angular/src/app/features/client/dashboard/client-dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterModule } from '@angular/router';
import { ClientPolicyService } from '../../../core/services/client-policy.service';
import { ClaimService } from '../../../core/services/claim.service';

interface DashboardStats {
    totalPolicies: number;
    activePolicies: number;
    pendingClaims: number;
}

@Component({
    selector: 'app-client-dashboard',
    standalone: true,
    imports: [CommonModule, RouterModule],
    templateUrl: './client-dashboard.component.html',
    styleUrls: ['./client-dashboard.component.scss']
})
export class ClientDashboardComponent implements OnInit {
    stats: DashboardStats = {
        totalPolicies: 0,
        activePolicies: 0,
        pendingClaims: 0
    };
    loading = true;

    constructor(
        private clientPolicyService: ClientPolicyService,
        private claimService: ClaimService,
        private router: Router
    ) { }

    ngOnInit(): void {
        this.fetchStats();
    }

    fetchStats(): void {
        this.clientPolicyService.getMyPolicies().subscribe({
            next: (policies) => {
                this.claimService.getMyClaims().subscribe({
                    next: (claims) => {
                        this.stats = {
                            totalPolicies: policies?.length || 0,
                            activePolicies: policies?.filter(p => p.status === 'ACTIVE').length || 0,
                            pendingClaims: claims?.filter(c => c.status === 'PENDING').length || 0
                        };
                        this.loading = false;
                    },
                    error: (error) => {
                        console.error('Error fetching claims:', error);
                        this.loading = false;
                    }
                });
            },
            error: (error) => {
                console.error('Error fetching policies:', error);
                this.loading = false;
            }
        });
    }

    navigateToAI(): void {
        this.router.navigate(['/client/corporate-ai']);
    }
}

<div *ngIf="loading" class="loading">
    <div class="spinner"></div>
</div>

<div *ngIf="!loading" class="dashboard-container container">
    <div class="dashboard-header fade-in">
        <h1>Client Dashboard</h1>
        <p>Manage your insurance policies and claims</p>
    </div>

    <div class="stats-grid fade-in">
        <div class="stat-card card">
            <div class="stat-icon">📋</div>
            <div class="stat-content">
                <h3>{{ stats.totalPolicies }}</h3>
                <p>Total Policies</p>
            </div>
        </div>

        <div class="stat-card card">
            <div class="stat-icon">✅</div>
            <div class="stat-content">
                <h3>{{ stats.activePolicies }}</h3>
                <p>Active Policies</p>
            </div>
        </div>

        <div class="stat-card card">
            <div class="stat-icon">⏳</div>
            <div class="stat-content">
                <h3>{{ stats.pendingClaims }}</h3>
                <p>Pending Claims</p>
            </div>
        </div>
    </div>

    <div class="quick-actions fade-in">
        <h2>Quick Actions</h2>
        <div class="actions-grid">
            <a routerLink="/client/buy-policy" class="action-card card card-hover">
                <div class="action-icon">🛒</div>
                <h3>Buy New Policy</h3>
                <p>Browse and purchase insurance policies</p>
            </a>

            <a routerLink="/client/my-policies" class="action-card card card-hover">
                <div class="action-icon">📄</div>
                <h3>My Policies</h3>
                <p>View and manage your policies</p>
            </a>

            <a routerLink="/client/claim" class="action-card card card-hover">
                <div class="action-icon">📝</div>
                <h3>File a Claim</h3>
                <p>Submit a new insurance claim</p>
            </a>

            <a routerLink="/client/profile" class="action-card card card-hover">
                <div class="action-icon">👤</div>
                <h3>Profile Settings</h3>
                <p>Update your account information</p>
            </a>
        </div>
    </div>

    <button class="ai-fab" (click)="navigateToAI()" title="Corporate AI Assistant">
        🤖
    </button>
</div>
