// frontend/src/pages/Admin/ManagePolicies.jsx
import { useState, useEffect } from 'react';
import { adminService } from '../../services';
import '../Client/MyPolicies.css';

const ManagePolicies = () => {
    const [policies, setPolicies] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState('');

    useEffect(() => {
        fetchPolicies();
    }, []);

    const fetchPolicies = async () => {
        try {
            const data = await adminService.getAllPolicies();
            setPolicies(data);
        } catch (err) {
            setError('Failed to load policies');
        } finally {
            setLoading(false);
        }
    };

    const handleDelete = async (policyId) => {
        if (!window.confirm('Are you sure you want to delete this policy?')) {
            return;
        }

        try {
            await adminService.deletePolicy(policyId);
            fetchPolicies();
            alert('Policy deleted successfully!');
        } catch (err) {
            alert('Failed to delete policy');
        }
    };

    if (loading) {
        return <div className="loading"><div className="spinner"></div></div>;
    }

    return (
        <div className="my-policies-container container">
            <div className="page-header">
                <h1 className="page-title fade-in">Manage Policies</h1>
                <a href="/admin/create-policy" className="btn btn-primary">
                    Create New Policy
                </a>
            </div>

            {error && <div className="error-message">{error}</div>}

            <div className="policies-table-container card fade-in">
                <table className="policies-table">
                    <thead>
                        <tr>
                            <th>Policy Name</th>
                            <th>Premium/Month</th>
                            <th>Coverage</th>
                            <th>Risk Level</th>
                            <th>Period Range</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {policies.map((policy) => (
                            <tr key={policy.id}>
                                <td>{policy.name}</td>
                                <td>{policy.premiumPerYear.toLocaleString()} Rupees</td>
                                <td>{policy.coverageAmount.toLocaleString()} Rupees</td>
                                <td>
                                    <span className={`badge badge-${policy.riskLevel.toLowerCase()}`}>
                                        {policy.riskLevel}
                                    </span>
                                </td>
                                <td>{policy.minPeriodYears}-{policy.maxPeriodYears} years</td>
                                <td>
                                    <div style={{ display: 'flex', gap: '0.5rem' }}>
                                        {policy.policyDocumentUrl && (
                                            <a
                                                href={policy.policyDocumentUrl}
                                                target="_blank"
                                                rel="noopener noreferrer"
                                                className="btn btn-sm btn-secondary"
                                            >
                                                View Doc
                                            </a>
                                        )}
                                        <button
                                            onClick={() => handleDelete(policy.id)}
                                            className="btn btn-sm btn-danger"
                                        >
                                            Delete
                                        </button>
                                    </div>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
};

export default ManagePolicies;

// frontend-angular/src/app/features/admin/manage-policies/manage-policies.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { AdminService } from '../../../core/services/admin.service';
import { Policy } from '../../../core/models/policy.model';

@Component({
  selector: 'app-manage-policies',
  standalone: true,
  imports: [CommonModule, RouterModule],
  template: `
    <div class="manage-policies-container container">
      <div class="page-header">
          <h1 class="page-title fade-in">Manage Policies</h1>
          <a routerLink="/admin/create-policy" class="btn btn-primary">
              Create New Policy
          </a>
      </div>

      <div *ngIf="errorMessage" class="error-message fade-in">
        {{ errorMessage }}
      </div>

      <div class="policies-table-container card fade-in">
          <table class="policies-table" *ngIf="policies.length > 0; else noPolicies">
              <thead>
                  <tr>
                      <th>Policy Name</th>
                      <th>Premium</th>
                      <th>Coverage</th>
                      <th>Risk Level</th>
                      <th>Period Range</th>
                      <th>Actions</th>
                  </tr>
              </thead>
              <tbody>
                  <tr *ngFor="let policy of policies">
                      <td>{{ policy.name }}</td>
                      <td>{{ policy.premiumPerYear | number }} Rupees</td>
                      <td>{{ policy.coverageAmount | number }} Rupees</td>
                      <td>
                          <span [class]="'badge badge-' + (policy.riskLevel?.toLowerCase() || 'medium')">
                              {{ policy.riskLevel || 'Medium' }}
                          </span>
                      </td>
                      <td>{{ policy.minPeriodYears }}-{{ policy.maxPeriodYears }} years</td>
                      <td>
                          <div class="actions">
                              <button
                                  class="btn btn-sm btn-primary"
                                  [routerLink]="['/admin/create-policy', policy.id]"
                              >
                                  Edit
                              </button>
                              <button
                                  class="btn btn-sm btn-danger"
                                  (click)="deletePolicy(policy.id)"
                              >
                                  Delete
                              </button>
                          </div>
                      </td>
                  </tr>
              </tbody>
          </table>
          <ng-template #noPolicies>
              <p style="padding: 2rem; text-align: center;">No policies found.</p>
          </ng-template>
      </div>
    </div>
  `,
  styleUrls: ['./manage-policies.component.scss']
})
export class ManagePoliciesComponent implements OnInit {
  policies: Policy[] = [];
  errorMessage: string = '';

  constructor(private adminService: AdminService) { }

  ngOnInit(): void {
    this.loadPolicies();
  }

  loadPolicies(): void {
    this.errorMessage = '';
    this.adminService.getAllPolicies().subscribe({
      next: (data) => this.policies = data,
      error: (err) => {
        console.error('Error loading policies', err);
        this.errorMessage = 'Failed to load policies. Please try again later.';
      }
    });
  }

  deletePolicy(id: number): void {
    if (confirm('Are you sure you want to delete this policy?')) {
      this.adminService.deletePolicy(id).subscribe({
        next: () => {
          alert('Policy deleted successfully!');
          this.loadPolicies();
        },
        error: () => alert('Failed to delete policy')
      });
    }
  }
}
