// frontend-angular/src/app/features/admin/dashboard/admin-dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterModule } from '@angular/router';
import { AdminService } from '../../../core/services/admin.service';

@Component({
  selector: 'app-admin-dashboard',
  standalone: true,
  imports: [CommonModule, RouterModule],
  template: `
    <div *ngIf="loading" class="loading"><div class="spinner"></div></div>
    <div *ngIf="!loading" class="dashboard-container container">
      <div class="dashboard-header fade-in">
        <h1>Admin Dashboard</h1>
        <p>Manage policies, claims, and clients</p>
      </div>

      <div class="stats-grid fade-in">
        <div class="stat-card card">
          <div class="stat-icon">📋</div>
          <div class="stat-content">
            <h3>{{ stats.totalPolicies }}</h3>
            <p>Total Policies</p>
          </div>
        </div>

        <div class="stat-card card">
          <div class="stat-icon">👥</div>
          <div class="stat-content">
            <h3>{{ stats.totalClients }}</h3>
            <p>Total Clients</p>
          </div>
        </div>

        <div class="stat-card card">
          <div class="stat-icon">⏳</div>
          <div class="stat-content">
            <h3>{{ stats.pendingClaims }}</h3>
            <p>Pending Claims</p>
          </div>
        </div>
      </div>

      <div class="quick-actions fade-in">
        <h2>Quick Actions</h2>
        <div class="actions-grid">
          <a routerLink="/admin/create-policy" class="action-card card card-hover">
            <div class="action-icon">➕</div>
            <h3>Create Policy</h3>
            <p>Add new insurance policy</p>
          </a>

          <a routerLink="/admin/policies" class="action-card card card-hover">
            <div class="action-icon">📄</div>
            <h3>Manage Policies</h3>
            <p>View and update policies</p>
          </a>

          <a routerLink="/admin/claims" class="action-card card card-hover">
            <div class="action-icon">📝</div>
            <h3>Manage Claims</h3>
            <p>Review and process claims</p>
          </a>

          <a routerLink="/admin/clients" class="action-card card card-hover">
            <div class="action-icon">👤</div>
            <h3>Manage Clients</h3>
            <p>View and manage client accounts</p>
          </a>
        </div>
      </div>

      <button class="ai-fab" (click)="navigateToAI()" title="Corporate AI Assistant">🤖</button>
    </div>
  `,
  styleUrls: ['./admin-dashboard.component.scss']
})
export class AdminDashboardComponent implements OnInit {
  stats = { totalPolicies: 0, totalClients: 0, pendingClaims: 0 };
  loading = true;

  constructor(private adminService: AdminService, private router: Router) { }

  ngOnInit(): void {
    this.adminService.getAllPolicies().subscribe({
      next: (policies) => {
        this.adminService.getAllClients().subscribe({
          next: (clients) => {
            this.adminService.getAllClaims('PENDING').subscribe({
              next: (claims) => {
                this.stats = {
                  totalPolicies: policies?.length || 0,
                  totalClients: clients?.length || 0,
                  pendingClaims: claims?.length || 0
                };
                this.loading = false;
              },
              error: () => this.loading = false
            });
          },
          error: () => this.loading = false
        });
      },
      error: () => this.loading = false
    });
  }

  navigateToAI(): void {
    this.router.navigate(['/admin/corporate-ai']);
  }
}

// frontend/src/pages/Admin/AdminDashboard.jsx
import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { adminService } from '../../services';
import '../Client/ClientDashboard.css';
import { useNavigate } from "react-router-dom";

const AdminDashboard = () => {
    const [stats, setStats] = useState({
        totalPolicies: 0,
        totalClients: 0,
        pendingClaims: 0,
    });
    const [loading, setLoading] = useState(true);
const navigate = useNavigate();

    useEffect(() => {
        const fetchStats = async () => {
            try {
                const [policies, clients, claims] = await Promise.all([
                    adminService.getAllPolicies(),
                    adminService.getAllClients(),
                    adminService.getAllClaims('PENDING'),
                ]);

                setStats({
                    totalPolicies: policies.length,
                    totalClients: clients.length,
                    pendingClaims: claims.length,
                });
            } catch (error) {
                console.error('Error fetching stats:', error);
            } finally {
                setLoading(false);
            }
        };

        fetchStats();
    }, []);

    if (loading) {
        return <div className="loading"><div className="spinner"></div></div>;
    }

    return (
        <div className="dashboard-container container">
            <div className="dashboard-header fade-in">
                <h1>Admin Dashboard</h1>
                <p>Manage policies, claims, and clients</p>
            </div>

            <div className="stats-grid fade-in">
                <div className="stat-card card">
                    <div className="stat-icon">📋</div>
                    <div className="stat-content">
                        <h3>{stats.totalPolicies}</h3>
                        <p>Total Policies</p>
                    </div>
                </div>

                <div className="stat-card card">
                    <div className="stat-icon">👥</div>
                    <div className="stat-content">
                        <h3>{stats.totalClients}</h3>
                        <p>Total Clients</p>
                    </div>
                </div>

                <div className="stat-card card">
                    <div className="stat-icon">⏳</div>
                    <div className="stat-content">
                        <h3>{stats.pendingClaims}</h3>
                        <p>Pending Claims</p>
                    </div>
                </div>
            </div>

            <div className="quick-actions fade-in">
                <h2>Quick Actions</h2>
                <div className="actions-grid">
                    <Link to="/admin/create-policy" className="action-card card card-hover">
                        <div className="action-icon">➕</div>
                        <h3>Create Policy</h3>
                        <p>Add new insurance policy</p>
                    </Link>

                    <Link to="/admin/policies" className="action-card card card-hover">
                        <div className="action-icon">📄</div>
                        <h3>Manage Policies</h3>
                        <p>View and update policies</p>
                    </Link>

                    <Link to="/admin/claims" className="action-card card card-hover">
                        <div className="action-icon">📝</div>
                        <h3>Manage Claims</h3>
                        <p>Review and process claims</p>
                    </Link>

                    <Link to="/admin/clients" className="action-card card card-hover">
                        <div className="action-icon">👤</div>
                        <h3>Manage Clients</h3>
                        <p>View and manage client accounts</p>
                    </Link>
                </div>
            </div>
  <button
  className="ai-fab"
  onClick={() => navigate("/admin/corporate-ai")}
  title="Corporate AI Assistant"
>
  🤖
</button>

        </div>
    );
};

export default AdminDashboard;
