// frontend-angular/src/app/features/admin/corporate-ai/corporate-ai-assistant.component.ts
import { Component, OnInit, ViewChild, ElementRef, AfterViewChecked } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../../core/services/auth.service';

interface Message {
  sender: 'user' | 'ai';
  text: string;
}

@Component({
  selector: 'app-corporate-ai-assistant',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="ai-root">
      <div class="ai-header">
        <h2>InsurAI Assistant</h2>
        <span class="role-badge admin">ADMIN</span>
      </div>

      <div class="ai-body">
        <!-- CHAT PANEL -->
        <div class="chat-panel">
          <div class="chat-window">
            <div *ngFor="let m of messages" class="chat-bubble" [ngClass]="m.sender">
              <p *ngFor="let line of m.text.split('\n')">{{ line }}</p>
            </div>

            <div *ngIf="loading" class="chat-bubble ai typing">
              <span></span>
              <span></span>
              <span></span>
            </div>

            <div #chatEndRef></div>
          </div>

          <div class="chat-input">
            <input
              placeholder="Ask about corporate insurance..."
              [(ngModel)]="input"
              (keydown.enter)="askAI()"
              [disabled]="loading"
            />
            <button (click)="askAI()" [disabled]="loading">
              Send
            </button>
          </div>
        </div>

        <!-- SUGGESTION PANEL -->
        <div class="suggestion-panel">
          <h4>Suggested Questions</h4>
          <div
            *ngFor="let q of suggested"
            class="suggestion-card"
            (click)="askAI(q)"
          >
            {{ q }}
          </div>
        </div>
      </div>
    </div>
  `,
  styleUrls: ['./corporate-ai-assistant.component.scss']
})
export class CorporateAiAssistantComponent implements OnInit, AfterViewChecked {
  @ViewChild('chatEndRef') chatEndRef!: ElementRef;

  messages: Message[] = [];
  input: string = '';
  suggested: string[] = [
    "List all system policies",
    "Show premium vs coverage comparison",
    "Which policies have high risk?",
    "Create a new corporate policy"
  ];
  loading: boolean = false;

  constructor(
    private http: HttpClient,
    private authService: AuthService
  ) { }

  ngOnInit(): void { }

  ngAfterViewChecked(): void {
    this.scrollToBottom();
  }

  scrollToBottom(): void {
    try {
      this.chatEndRef.nativeElement.scrollIntoView({ behavior: 'smooth' });
    } catch (err) { }
  }

  askAI(question?: string): void {
    const text = question || this.input;
    if (!text.trim()) return;

    if (!this.authService.isAuthenticated()) {
      this.messages.push({ sender: 'ai', text: "Authentication required. Please log in." });
      return;
    }

    this.messages.push({ sender: 'user', text });
    this.input = '';
    this.loading = true;

    // API Call
    // Assuming the backend is on localhost:8080 as per React code
    const url = 'http://localhost:8080/api/ai/admin-recommendation';

    const token = this.authService.getToken();
    const headers = {
      'Authorization': `Bearer ${token}`,
      'Content-Type': 'application/json'
    };

    this.http.post<any>(url, { input: text }, { headers }).subscribe({
      next: (res) => {
        this.messages.push({ sender: 'ai', text: res.response || "No response from AI." });
        this.loading = false;
      },
      error: (err) => {
        console.error("AI ERROR:", err);
        const errorMsg = err.error?.response || err.error?.message || "AI service failed. Please try again.";
        this.messages.push({ sender: 'ai', text: errorMsg });
        this.loading = false;
      }
    });
  }
}

// frontend/src/pages/Admin/CorporateAiAssistant.jsx
import React, { useState, useEffect, useRef } from "react";
import axios from "axios";
import "./CorporateAiAssistant.css";
import { useAuth } from "../../context/AuthContext";

const CorporateAiAssistant = ({ userType = "ADMIN" }) => {
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState("");
  const [suggested, setSuggested] = useState([]);
  const [loading, setLoading] = useState(false);
  const chatEndRef = useRef(null);

  const { token } = useAuth();
  const isReady = Boolean(token);

  /* ---------------- AUTO SCROLL ---------------- */
  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, loading]);

  /* ---------------- SUGGESTED QUESTIONS ---------------- */
  useEffect(() => {
    setSuggested(
      userType.toUpperCase() === "ADMIN"
        ? [
            "List all system policies",
            "Show premium vs coverage comparison",
            "Which policies have high risk?",
            "Create a new corporate policy",
          ]
        : [
            "Which policies do I currently have?",
            "What is my coverage amount?",
            "When does my policy expire?",
            "How can I file a claim?",
          ]
    );
  }, [userType]);

  /* ---------------- ASK AI ---------------- */
  const askAI = async (question) => {
    const text = question || input;
    if (!text.trim()) return;

    if (!isReady) {
      setMessages((prev) => [
        ...prev,
        { sender: "ai", text: "Authentication required. Please log in." },
      ]);
      return;
    }

    setMessages((prev) => [...prev, { sender: "user", text }]);
    setInput("");
    setLoading(true);

    const url =
      userType.toUpperCase() === "ADMIN"
        ? "http://localhost:8080/api/ai/admin-recommendation"
        : "http://localhost:8080/api/ai/client-recommendation";

    const payload = { input: text }; // send only the question

    try {
      const res = await axios.post(url, payload, {
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "application/json",
        },
      });

      setMessages((prev) => [
        ...prev,
        { sender: "ai", text: res.data?.response || "No response from AI." },
      ]);
    } catch (err) {
      console.error("AI ERROR:", err.response?.data || err.message);

      setMessages((prev) => [
        ...prev,
        {
          sender: "ai",
          text:
            err.response?.data?.response ||
            err.response?.data?.message ||
            "AI service failed. Please try again.",
        },
      ]);
    } finally {
      setLoading(false);
    }
  };

  /* ---------------- UI ---------------- */
  return (
    <div className="ai-root">
      <div className="ai-header">
        <h2>InsurAI Assistant</h2>
        <span className={`role-badge ${userType.toLowerCase()}`}>
          {userType.toUpperCase()}
        </span>
      </div>

      <div className="ai-body">
        {/* CHAT PANEL */}
        <div className="chat-panel">
          <div className="chat-window">
            {messages.map((m, i) => (
              <div key={`msg-${i}`} className={`chat-bubble ${m.sender}`}>
                {m.text.split("\n").map((line, idx) => (
                  <p key={`line-${idx}`}>{line}</p>
                ))}
              </div>
            ))}

            {loading && (
              <div className="chat-bubble ai typing">
                <span></span>
                <span></span>
                <span></span>
              </div>
            )}

            <div ref={chatEndRef} />
          </div>

          <div className="chat-input">
            <input
              placeholder="Ask about corporate insurance..."
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && askAI()}
              disabled={loading || !isReady}
            />
            <button onClick={() => askAI()} disabled={loading || !isReady}>
              Send
            </button>
          </div>
        </div>

        {/* SUGGESTION PANEL */}
        <div className="suggestion-panel">
          <h4>Suggested Questions</h4>
          {suggested.map((q, i) => (
            <div
              key={`suggestion-${i}`}
              className="suggestion-card"
              onClick={() => isReady && askAI(q)}
            >
              {q}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default CorporateAiAssistant;
